
package cliente;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Conversor", targetNamespace = "http://control/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Conversor {


    /**
     * 
     * @param milhas
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "milhasParaKilometros", targetNamespace = "http://control/", className = "cliente.MilhasParaKilometros")
    @ResponseWrapper(localName = "milhasParaKilometrosResponse", targetNamespace = "http://control/", className = "cliente.MilhasParaKilometrosResponse")
    @Action(input = "http://control/Conversor/milhasParaKilometrosRequest", output = "http://control/Conversor/milhasParaKilometrosResponse")
    public String milhasParaKilometros(
        @WebParam(name = "milhas", targetNamespace = "")
        float milhas);

    /**
     * 
     * @param kilometros
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "kilometrosParaMilhas", targetNamespace = "http://control/", className = "cliente.KilometrosParaMilhas")
    @ResponseWrapper(localName = "kilometrosParaMilhasResponse", targetNamespace = "http://control/", className = "cliente.KilometrosParaMilhasResponse")
    @Action(input = "http://control/Conversor/kilometrosParaMilhasRequest", output = "http://control/Conversor/kilometrosParaMilhasResponse")
    public String kilometrosParaMilhas(
        @WebParam(name = "kilometros", targetNamespace = "")
        float kilometros);

}
